### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by frederikcoppens** [elixir-europe/EIP-data-validation#1]
I did not yet put a licence on the repo, which licence do we add ?

**Comment by cpommier** [comment]
MIT is nice but involves copyright (Elixir ?). 
AGPL might be the better choice. I can check the compatibility between AGPL, MIT and Apache if you want.

**Comment by cpommier** [comment]
CC By for document seems better

**Comment by mcourtot** [comment]
Done.
